kind: pipeline
name: deploy-app

trigger:
  branch:
    - master
  event:
    - push

volumes:
  - name: docker_daemon
    host:
      path: /var/run/docker.sock
  - name: docker_cache
    host:
      path: /mnt/drone-docker

steps:
  - name: build-app
    image: docker:dind
    environment:
      REGISTRY_USER:
        from_secret: docker_username
      REGISTRY_PASS:
        from_secret: docker_password
    volumes:
      - name: docker_cache
        path: /var/lib/docker
      - name: docker_daemon
        path: /var/run/docker.sock
    commands:
      - docker login -u $REGISTRY_USER -p $REGISTRY_PASS registry.vivifyideas.com
      - docker build -t deploy-app-builder --target builder --pull .
      - docker build -t registry.vivifyideas.com/deploy/app:${DRONE_BRANCH} --pull .
      - docker push registry.vivifyideas.com/deploy/app:${DRONE_BRANCH}
      - docker image prune -f

  - name: deploy
    image: alpine
    commands:
      - apk add --no-cache curl
      - sh deploy.sh

  - name: slack
    image: plugins/slack
    when:
      status: [ success, failure ]
    settings:
      webhook:
        from_secret: slack_webhook
      channel: deploy

