version: '3'
services:
  app:
    build: .
    container_name: deploy-app
    deploy:
     restart_policy:
       condition: on-failure
    environment:
      NGINX_SERVER_NAME: _
    ports:
      - 80:80

